# Site settings
title: 防诈骗
SEOTitle: 防诈骗
header-img: img/post-bg-desk.jpg
email: combatingfraud@outlook.com
description: "防诈骗知识库"
keyword: "防诈骗, 反诈, 安全"
url: "https://xmengjun.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/xmengjun/xmengjun.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "保持警惕,守护安全"
sidebar-avatar: /img/logo.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     xmengjun
# zhihu_username:     xmengjun
github_username:    xmengjun
# facebook_username:  xmengjun
# jianshu_username:   xmengjun
# twitter_username:   xmengjun




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 57b04cca031212e0295f                            #生成的clientID
  clientSecret: 4f41b1df7282567c1453ba73b1396d9d897e9914    #生成的clientSecret
  repo: xmengjun.github.io    #仓库名称
  owner: xmengjun    #github用户名
  admin: xmengjun
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: 315e6eceffe95d91e6dc8030777e169e

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# 友情链接，请尽量不要删除，谢谢！
friends: [
    {
        title: "原子空间",
        href: "https://everygogo.com"
    },{
        title: "默库",
        href: "https://everygg.com"
    }
]
